"""add row type to bitcoin_daily_candles

Revision ID: ec3a983e65fc
Revises: 7bf9cf4a4548
Create Date: 2026-02-06 15:07:46.555159

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec3a983e65fc"
down_revision: str | Sequence[str] | None = "7bf9cf4a4548"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bitcoin_daily_candles", sa.Column("type", sa.String(length=1), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bitcoin_daily_candles", "type")
    # ### end Alembic commands ###
